# Generated by Django 2.2.6 on 2020-02-05 06:07

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('costoadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manodeobraindirecta',
            name='salario',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BSS', max_digits=19),
        ),
    ]
