# Generated by Django 2.2.6 on 2020-02-06 07:00

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('costoadmin', '0002_auto_20200205_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialesindirectos',
            name='costo',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BSS', max_digits=19),
        ),
        migrations.AlterField(
            model_name='serviciosindirectos',
            name='costo',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BSS', max_digits=19),
        ),
    ]
