# Generated by Django 2.2.6 on 2020-02-06 07:00

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('costope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='manodeobradirecta',
            name='cargo',
            field=models.CharField(max_length=150, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='materialesdirectos',
            name='costo',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BSS', max_digits=19),
        ),
        migrations.AlterField(
            model_name='materialesdirectos',
            name='material',
            field=models.CharField(max_length=150, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='costo',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BSS', max_digits=19),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='materia',
            field=models.CharField(max_length=150, verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='serviciosdirectos',
            name='costo',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BSS', max_digits=19),
        ),
        migrations.AlterField(
            model_name='serviciosdirectos',
            name='servicio',
            field=models.CharField(max_length=150, verbose_name='Servicio'),
        ),
    ]
